[versions]
kotlin = "2.3.10"
agp = "9.0.0"
compose = "1.11.0-alpha02"
ktor = "3.4.0"
androidxLifecycle = "2.10.0-alpha08"
landscapist = "2.9.3"

[libraries]
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
landscapist-animation = { module = "com.github.skydoves:landscapist-animation", version.ref = "landscapist" }
landscapist-image = { module = "com.github.skydoves:landscapist-image", version.ref = "landscapist" }
landscapist-placeholder = { module = "com.github.skydoves:landscapist-placeholder", version.ref = "landscapist" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }

androidx-navigation = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version = "1.0.0-alpha06" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }

compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose" }
materialKolor = { module = "com.materialkolor:material-kolor", version = "5.0.0-alpha06" }
hypnoticcanvas = { module = "com.mikepenz.hypnoticcanvas:hypnoticcanvas", version = "0.4.1" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.10.0" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.12.3" }

kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version = "1.10.2" }
brahmkshatriya-betterwindow = { module = "dev.brahmkshatriya:betterwindow", version = "1.1.0" }


[bundles]
compose = ["compose-runtime", "compose-foundation", "compose-components-resources", "ui", "ui-tooling", "compose-material3", "ui-tooling-preview"]
landscapist = ["landscapist-image", "landscapist-animation", "landscapist-placeholder"]
parsing = ["kotlinx-serialization-json"]
lifecycle = ["androidx-lifecycle-viewmodelCompose", "androidx-lifecycle-runtimeCompose"]

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

composeHotReload = { id = "org.jetbrains.compose.hot-reload", version = "1.0.0" }
composeMultiplatform = { id = "org.jetbrains.compose", version = "1.10.0" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

stabilityAnalyzer = { id = "com.github.skydoves.compose.stability.analyzer", version = "0.6.6" }

androidKMPLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

kotlinJVM = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }