[versions]
agp = "8.12.2"
kotlin = "2.2.10"

androidx-paging = "3.3.6"
room = "2.7.2"
koinAndroid = "4.1.0"
media3 = "1.8.0"
coil = "3.3.0"

accompanist = "0.3.4"
jaudiotagger = "2.2.5"

[libraries]
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.1.0" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.9.0" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.10.2" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

androidx-core-google-shortcuts = { module = "androidx.core:core-google-shortcuts", version = "1.1.0" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
androidx-activity = { group = "androidx.activity", name = "activity", version = "1.10.1" }

protobuf-java = { module = "com.google.protobuf:protobuf-java", version = "4.32.0" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.4.0" }
swiperefresh = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version = "1.1.0" }

fragment = { module = "androidx.fragment:fragment-ktx", version = "1.8.9" }

splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }
palette = { module = "androidx.palette:palette-ktx", version = "1.0.0" }
material = { group = "com.google.android.material", name = "material", version = "1.14.0-alpha04" }

preference = { module = "androidx.preference:preference-ktx", version = "1.2.1" }

paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "androidx-paging" }
paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx-paging" }

filekache = { module = "com.mayakapps.kache:file-kache", version = "2.1.1" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

koin-androidx-startup = { module = "io.insert-koin:koin-androidx-startup", version.ref = "koinAndroid" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koinAndroid" }

media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
media3-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
media3-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }

coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

pikolo = { module = "com.github.madrapps:pikolo", version = "2.0.2" }
fadingedgelayout = { module = "com.github.bosphere.android-fadingedgelayout:fadingedgelayout", version = "1.0.0" }
fastscroll = { module = "me.zhanghai.android.fastscroll:library", version = "1.3.0" }
kenburnsview = { module = "com.flaviofaria:kenburnsview", version = "1.0.7" }
nestedscrollwebview = { module = "com.telefonica:nestedscrollwebview", version = "0.1.6" }
acsbendi-webview = { module = "com.github.acsbendi:Android-Request-Inspector-WebView", version = "1.0.12" }

firebase-analytics = { module = "com.google.firebase:firebase-analytics", version = "23.0.0" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version = "20.0.1" }

accompanist-core = { module = "com.mocharealm.accompanist:lyrics-core", version.ref = "accompanist"}
jaudiotagger = { module = "net.jthink:jaudiotagger", version.ref = "jaudiotagger" }
[bundles]
androidx = [
    "androidx-core-ktx", "androidx-appcompat", "androidx-activity", "fragment",
    "recyclerview", "swiperefresh",
    "splashscreen", "palette",
    "preference",
    "androidx-core-google-shortcuts"
]
paging = ["paging-common", "paging-runtime"]
room = ["room-runtime", "room-ktx"]
koin = ["koin-androidx-startup", "koin-android", "koin-androidx-workmanager"]
media3 = ["media3-exoplayer", "media3-session", "media3-ui", "media3-dash", "media3-hls"]
coil = ["coil", "coil-gif", "coil-svg", "coil-network-okhttp"]
kotlinx = ["kotlinx-serialization-json", "kotlinx-coroutines-core"]
firebase = ["firebase-analytics", "firebase-crashlytics"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.2.10-2.0.2" }
gms = { id = "com.google.gms.google-services", version = "4.4.3" }
crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.6" }
